version: '3'
services:
  nginx:
    build:
      context: ./
      dockerfile: ./config/docker/dockerfiles/nginx/Dockerfile
      args:
        TZ: ${TZ:-America/New_York}
        NGINX_VERSION: ${NGINX_VERSION:-stable-alpine}
    container_name: related_blog-nginx
    ports:
      - '8000:80'
    volumes:
      - ./config/docker/etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro,cached
      - ./config/docker/etc/nginx/global:/etc/nginx/global:ro,cached
      - ./config/docker/etc/nginx/wordpress:/etc/nginx/wordpress:ro,cached
      - ./config/docker/etc/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro,cached
      - ./data/logs/nginx:/var/log/nginx
      - .:/var/www/html:rw,cached
    depends_on:
      - php
    restart: always

  php:
    build:
      context: ./
      dockerfile: ./config/docker/dockerfiles/php/Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION:-7}
        MEMCACHED_EXT_VERSION: ${MEMCACHED_EXT_VERSION:-3.1.3}
        REDIS_EXT_VERSION: ${REDIS_EXT_VERSION:-4.1.1}
        XDEBUG_EXT_VERSION: ${XDEBUG_EXT_VERSION:-beta}
        TZ: ${TZ:-America/New_York}
    container_name: related_blog-php
    volumes:
      - .:/var/www/html:rw,cached
      - ./config/docker/dockerfiles/php/.bashrc:/root/.bashrc:rw,cached
      - ./config/docker/etc/php/php.ini:/usr/local/etc/php/php.ini:rw,cached
      - ./config/docker/etc/php/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf:ro,cached
      - ./config/docker/etc/php/conf.d/mysqli.ini:/usr/local/etc/php/conf.d/mysqli.ini:ro,cached
      - ./config/docker/etc/php/conf.d/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini:ro,cached
      - ./config/docker/etc/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro,cached
      - ./data/logs/php:/var/log/php:rw,delegated
    environment:
      DB_NAME: ${DB_NAME:-wordpress}
      DB_USER: ${DB_USER:-root}
      DB_PASSWORD: ${DB_PASSWORD:-password}
      DB_HOST: ${DB_HOST:-mysql}
      DB_PORT: ${DB_PORT:-3306}
      DB_PREFIX: ${DB_PREFIX:-wp_}
      CACHE_HOST: ${REDIS_HOST:-redis}
      CACHE_PORT: ${REDIS_PORT:-6379}
      CACHE_PASSWORD: ${REDIS_PASSWORD:-}
      XDEBUG_CONFIG: remote_host=192.168.65.2
    restart: always
    # cap and privileged needed for slowlog
    cap_add:
      - SYS_PTRACE
    privileged: true

  mysql:
    image: mariadb:${MARIADB_VERSION:-latest}
    container_name: related_blog-mysql
    ports:
      - '3306:3306'
    volumes:
      - ./data/db:/var/lib/mysql
      - ./config/docker/etc/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro,cached
    environment:
      MYSQL_DATABASE: ${DB_NAME:-wordpress}
      MYSQL_USER: ${DB_USER:-root}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-password}
    links:
      - php
    restart: always

  redis:
    image: redis:${REDIS_VERSION:-alpine}
    container_name: related_blog-redis
    ports:
      - '6379:6379'
    volumes:
      - ./config/docker/etc/redis/redis.conf:/etc/redis.conf:ro,cached
      - ./data/redis:/data:rw,delegated
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'
    restart: always
    depends_on:
      - mysql
    entrypoint: ["redis-server", "/etc/redis.conf"]
