version: '3'
services:
  nginx:
    image: nginx:${NGINX_VERSION:-latest}
    container_name: related_blog-nginx
    ports:
      - '8000:80'
    volumes:
      - ${NGINX_CONF:-./config/nginx/default.conf}:/etc/nginx/conf.d/default.conf
      - ${NGINX_LOG_DIR:-./data/logs/nginx}:/var/log/nginx
      - ${APP_DIR:-.}:/var/www/html:${VOLUME_FLAGS-rw,cached}
    depends_on:
      - php
    restart: always

  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: related_blog-php
    volumes:
      - ${APP_DIR:-.}:/var/www/html:${VOLUME_FLAGS-rw,cached}
      - ./config/php/max_execution_time.ini:/usr/local/etc/php/conf.d/max_execution_time.ini
      - ./config/php/memory_limit.ini:/usr/local/etc/php/conf.d/memory_limit.ini
      - ./config/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    environment:
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME:-wordpress}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX:-wp_}
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST:-mysql:3306}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER:-root}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD:-password}
    restart: always

  mysql:
    image: mariadb:${MARIADB_VERSION:-latest}
    container_name: related_blog-mysql
    ports:
      - '3306:3306'
    volumes:
      - ./data/db:/var/lib/mysql
      - ./config/mysql/extra.cnf:/etc/mysql/conf.d/extra.cnf
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password}
      MYSQL_USER: ${MYSQL_USER:-root}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-wordpress}
    links:
      - php
    restart: always
